/* eslint-disable */
// @ts-nocheck
"use client";

import { useState, useEffect } from 'react';
import { PawPrint, Loader2, ExternalLink, ShieldCheck } from 'lucide-react';

export default function RescuesPage() {
  const [campaigns, setCampaigns] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedCampaign, setSelectedCampaign] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/campaigns')
      .then(res => res.json())
      .then(data => {
        if (data.success) setCampaigns(data.data);
        setLoading(false);
      });
  }, []);

  if (loading) {
    return <div className="flex h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-accent" /></div>;
  }

  return (
    <div className="mx-auto w-full max-w-7xl px-4 py-8 lg:px-6">
      <div className="mb-12">
        <h1 className="text-3xl font-medium tracking-tight text-primary">Live Rescues & Proof of Impact</h1>
        <p className="mt-2 text-muted-foreground">Every dollar generated by our smart contracts is verifiable on-chain.</p>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {campaigns.map((camp) => (
          <div key={camp.id} className="group relative overflow-hidden rounded-2xl border border-border bg-card shadow-sm transition-all hover:border-accent/50">
            {/* Background Image */}
            <div 
              className="absolute inset-0 z-0 opacity-20 transition-opacity group-hover:opacity-30"
              style={{ backgroundImage: `url(${camp.image})`, backgroundSize: 'cover', backgroundPosition: 'center' }}
            />
            
            <div className="relative z-10 flex h-full flex-col p-6">
              <div className="mb-auto">
                <span className="mb-3 inline-block rounded-full bg-secondary px-3 py-1 text-xs font-medium text-primary">
                  {camp.shelter}
                </span>
                <h3 className="text-xl font-bold text-primary">{camp.name}</h3>
              </div>

              <div className="mt-8 space-y-3">
                <div className="flex justify-between text-sm font-medium">
                  <span className="text-green-500">${camp.raised.toLocaleString()} Raised</span>
                  <span className="text-muted-foreground">Goal: ${camp.goal.toLocaleString()}</span>
                </div>
                
                <div className="h-3 w-full overflow-hidden rounded-full bg-secondary">
                  <div 
                    className="h-full bg-accent transition-all duration-1000"
                    style={{ width: `${Math.min((camp.raised / camp.goal) * 100, 100)}%` }}
                  />
                </div>
              </div>

              {/* Receipts Drawer Toggle */}
              <button 
                onClick={() => setSelectedCampaign(selectedCampaign === camp.id ? null : camp.id)}
                className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border border-border bg-background py-3 text-sm font-medium text-primary transition-colors hover:bg-secondary/50"
              >
                <ShieldCheck className="h-4 w-4 text-accent" />
                {selectedCampaign === camp.id ? "Hide Receipts" : "View On-Chain Receipts"}
              </button>

              {/* Expanding Receipts Drawer */}
              {selectedCampaign === camp.id && (
                <div className="mt-4 animate-in fade-in slide-in-from-top-2 rounded-xl bg-background p-4 text-xs border border-border/50 space-y-3">
                  <h4 className="font-bold text-muted-foreground uppercase tracking-widest text-[10px]">Verified Vault Withdrawals</h4>
                  
                  {/* Mock Receipts based on the campaign id */}
                  <div className="flex items-center justify-between border-b border-border/50 pb-2">
                    <span className="text-green-500 font-mono">+ $1,250 USDC</span>
                    <a href="#" className="flex items-center gap-1 text-muted-foreground hover:text-accent transition-colors">
                      Solscan <ExternalLink className="h-3 w-3" />
                    </a>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-green-500 font-mono">+ $300 USDC</span>
                    <a href="#" className="flex items-center gap-1 text-muted-foreground hover:text-accent transition-colors">
                      Solscan <ExternalLink className="h-3 w-3" />
                    </a>
                  </div>
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
